"use client";

import { useState } from "react";
import Link from "next/link";
import { BusinessVisual } from "@/components/business-visual";
import { InteriorShell } from "@/components/interior-shell";
import { estimateMonthlyTime } from "@/lib/business-tools";
import type { Locale, NeedId } from "@/lib/types";
import styles from "./business-discovery.module.css";

export function BusinessTools({ locale }: { locale: Locale }) {
  const es = locale === "es";
  const [sector, setSector] = useState("commerce");
  const [need, setNeed] = useState<NeedId>("ordenar");
  const [stage, setStage] = useState("operation");
  const [values, setValues] = useState(["10", "6", "22", "25"]);
  const estimate = estimateMonthlyTime(...values.map(value => value.trim() === "" ? NaN : Number(value)) as [number, number, number, number]);
  const number = new Intl.NumberFormat(es ? "es-DO" : "en-US", { maximumFractionDigits: 1 });
  const actions = need === "crecer"
    ? (es ? ["Elige un público y aclara por qué debería elegirte.", "Revisa cómo una visita se convierte en una consulta.", "Define quién responde y cómo se da seguimiento."] : ["Choose an audience and clarify why they should choose you.", "Review how a visit becomes an inquiry.", "Define who responds and how follow-up works."])
    : need === "cumplir"
      ? (es ? ["Identifica los registros disponibles y los pendientes.", "Aclara responsables y fechas de revisión.", "Valida la información con el profesional correspondiente."] : ["Identify available and missing records.", "Clarify responsibilities and review dates.", "Validate the information with the appropriate professional."])
      : sector === "commerce"
        ? (es ? ["Documenta una venta y el cierre del día.", "Revisa cómo se actualizan las existencias.", "Define qué necesitas controlar antes de elegir un sistema."] : ["Document a sale and the daily close.", "Review how stock levels are updated.", "Define what you need to control before choosing a system."])
        : sector === "print" ? (es ? ["Define especificaciones y aprobación de cada pedido.", "Conecta materiales, costos y etapas de producción.", "Asigna responsables de revisión y entrega."] : ["Define specifications and approval for every order.", "Connect materials, costs and production stages.", "Assign owners for review and delivery."])
        : (es ? ["Dibuja el recorrido desde la consulta hasta la entrega.", "Aclara responsables, propuestas y aprobaciones.", "Reúne la información antes de automatizar."] : ["Map the journey from inquiry to delivery.", "Clarify owners, proposals and approvals.", "Bring information together before automating."]);
  const stageAdvice = stage === "start" ? (es ? "Si estás comenzando, valida primero una necesidad concreta de tu cliente." : "If you are starting, validate a specific customer need first.") : stage === "growth" ? (es ? "Si estás ampliando, documenta permisos y seguimiento entre equipos." : "If you are expanding, document permissions and follow-up across teams.") : (es ? "Si ya estás operando, empieza por el paso que más retrabajo genera." : "If you are already operating, start with the step that creates the most rework.");
  const intakeSector = ({ commerce: "comercio", services: "servicios", print: "imprenta", other: "otro" })[sector];
  const saveRoute = () => {
    const sectorLabel = ({ commerce: es ? "Comercio" : "Retail", services: es ? "Servicios" : "Services", print: es ? "Imprenta" : "Print", other: es ? "Otro negocio" : "Other business" })[sector];
    const content = [es ? "Mi ruta RCP" : "My RCP route", sectorLabel, ...actions.map((action, index) => `${index + 1}. ${action}`), stageAdvice, es ? "Orientación general; requiere evaluación humana. No es una cotización." : "General guidance; requires human assessment. Not a quote.", "https://rcp.services"].join("\n\n");
    const url = URL.createObjectURL(new Blob([content], { type: "text/plain;charset=utf-8" }));
    const link = document.createElement("a"); link.href = url; link.download = es ? "mi-ruta-rcp.txt" : "my-rcp-route.txt"; document.body.append(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  return <InteriorShell locale={locale}><div className={styles.page}>
    <section className="interior-hero"><div className="container interior-hero__grid"><div><p className="section-eyebrow">{es ? "Herramientas para decidir" : "Tools for better decisions"}</p><h1>{es ? "Un primer paso más claro." : "A clearer first step."}</h1><p>{es ? "Explora tu prioridad y dimensiona una tarea repetitiva antes de pensar en contratar una solución." : "Explore your priority and measure a repetitive task before choosing a solution."}</p><div className="editorial-hero-actions"><a className="button button--primary" href="#orientation-title">{es ? "Encontrar mi ruta" : "Find my route"} ↗</a></div></div><BusinessVisual locale={locale} /></div></section>
    <section className={`container ${styles.tool}`} aria-labelledby="orientation-title"><div><span className={styles.number}>01</span><h2 id="orientation-title">{es ? "Ubica tu punto de partida." : "Find your starting point."}</h2><p>{es ? "Tres decisiones, una ruta inicial. No necesitas dejar datos personales." : "Three decisions, one initial route. No personal details needed."}</p>
      <label>{es ? "Tu negocio" : "Your business"}<select value={sector} onChange={event => setSector(event.target.value)}><option value="commerce">{es ? "Comercio" : "Retail business"}</option><option value="print">{es ? "Imprenta y producción" : "Print and production"}</option><option value="other">{es ? "Otro negocio" : "Other business"}</option><option value="services">{es ? "Empresa de servicios" : "Service business"}</option></select></label>
      <label>{es ? "Tu prioridad" : "Your priority"}<select value={need} onChange={event => setNeed(event.target.value as NeedId)}><option value="ordenar">{es ? "Ordenar mi operación" : "Organize my operations"}</option><option value="cumplir">{es ? "Organizar información y responsabilidades" : "Organize records and responsibilities"}</option><option value="crecer">{es ? "Conectar con más clientes" : "Connect with more customers"}</option></select></label>
      <label>{es ? "Tu etapa" : "Your stage"}<select value={stage} onChange={event => setStage(event.target.value)}><option value="start">{es ? "Estoy comenzando" : "Getting started"}</option><option value="operation">{es ? "Ya estoy operando" : "Already operating"}</option><option value="growth">{es ? "Estoy ampliando" : "Expanding"}</option></select></label></div>
      <div className={styles.result} aria-live="polite"><p className="section-eyebrow">{es ? "Tu ruta inicial" : "Your initial route"}</p><h3>{es ? "Empieza por aquí." : "Start here."}</h3><ol>{actions.map(action => <li key={action}>{action}</li>)}</ol><p>{stageAdvice}</p><p className={styles.note}>{es ? "Orientación general. El equipo confirma el alcance contigo durante la evaluación." : "General guidance. The team confirms the scope with you during the assessment."}</p><Link className="button button--primary" href={es ? `/diagnostico?necesidad=${need}&sector=${intakeSector}#solicitud` : `/en/diagnosis?need=${need}&sector=${intakeSector}#solicitud`}>{es ? "Conversar sobre esta prioridad" : "Discuss this priority"} ↗</Link><button className="save-route" type="button" onClick={saveRoute}>{es ? "Guardar mi ruta sin registro" : "Save my route without registering"} ↓</button><small>{es ? "45 minutos · Sin costo · Sujeta a confirmación" : "45 minutes · No cost · Subject to confirmation"}</small></div></section>
    <section className={`container ${styles.tool}`} aria-labelledby="calculator-title"><div><span className={styles.number}>02</span><h2 id="calculator-title">{es ? "¿Cuánto tiempo ocupa esa tarea?" : "How much time does that task take?"}</h2><p>{es ? "Usa tus propios datos y ajusta el escenario de reducción que quieres explorar." : "Use your own figures and adjust the reduction scenario you want to explore."}</p><div className={styles.inputs}>{(es ? ["Veces por día", "Minutos por tarea", "Días al mes", "Reducción a explorar (%)"] : ["Times per day", "Minutes per task", "Days per month", "Reduction to explore (%)"]).map((label, index) => <label key={label}>{label}<input type="number" inputMode="decimal" min={index === 3 ? 0 : 1} max={[500, 120, 31, 100][index]} step={index === 1 || index === 3 ? "any" : 1} value={values[index]} onChange={event => setValues(previous => previous.map((value, i) => i === index ? event.target.value : value))} /></label>)}</div></div>
      <div className={styles.result} aria-live="polite">{estimate ? <><p>{es ? "Tiempo mensual actual" : "Current monthly time"}</p><strong className={styles.metric}>{number.format(estimate.current)} <span>h</span></strong><p>{es ? "Horas que liberarías si alcanzas la reducción indicada" : "Hours freed if you achieve the selected reduction"}</p><strong className={styles.metric}>{number.format(estimate.potential)} <span>h</span></strong></> : <p role="status">{es ? "Completa los cuatro valores dentro de los límites: 1–500 tareas, 1–120 minutos, 1–31 días enteros y 0–100 % de reducción." : "Enter all four values within the limits: 1–500 whole tasks, 1–120 minutes, 1–31 whole days and 0–100% reduction."}</p>}<p className={styles.note}>{es ? "Cálculo: veces × minutos × días ÷ 60. Es un escenario basado en tus supuestos; no una promesa de ahorro ni una cotización. Los datos permanecen en esta página." : "Formula: times × minutes × days ÷ 60. This is a scenario based on your assumptions, not a savings promise or quote. The figures stay on this page."}</p><Link className="text-link" href={es ? "/software-a-la-medida?solucion=automatizacion-datos" : "/en/custom-software?solution=automation-data"}>{es ? "Explorar automatización con RCP" : "Explore automation with RCP"} ↗</Link></div></section>
  </div></InteriorShell>;
}
