import Image from "next/image";
import Link from "next/link";
import { InteriorShell } from "@/components/interior-shell";
import { createPublicPageMetadata } from "@/lib/metadata";
import type { Locale } from "@/lib/types";
import styles from "./business-discovery.module.css";

export type Audience = "commerce" | "services";
export const sectorPaths = {
  commerce: { es: "/soluciones/comercios", en: "/en/solutions/retail" },
  services: { es: "/soluciones/empresas-de-servicios", en: "/en/solutions/service-businesses" },
};
export function sectorMetadata(audience: Audience, locale: Locale) {
  const title = audience === "commerce" ? { es: "Soluciones para comercios", en: "Solutions for retail businesses" } : { es: "Soluciones para empresas de servicios", en: "Solutions for service businesses" };
  return createPublicPageMetadata({ locale, title: title[locale], description: locale === "es" ? "Conecta operación, estrategia y presencia digital con una ruta que comienza por la realidad de tu negocio." : "Connect operations, strategy and digital presence with a route that starts with your business reality.", canonical: sectorPaths[audience][locale], paths: sectorPaths[audience] });
}
export function BusinessSector({ audience, locale }: { audience: Audience; locale: Locale }) {
  const es = locale === "es";
  const commerce = audience === "commerce";
  const title = commerce ? (es ? "Vender, atender y tener el control." : "Sell, serve and stay in control.") : (es ? "De la primera consulta a una entrega clara." : "From the first inquiry to a clear delivery.");
  const steps = commerce ? (es ? ["Revisar el recorrido de una venta, desde la atención hasta el cierre.", "Conectar productos, existencias y responsables.", "Aclarar la oferta y facilitar que el cliente pregunte o compre."] : ["Review a sale from customer service to the daily close.", "Connect products, stock levels and responsibilities.", "Clarify the offer and make it easier to inquire or buy."]) : (es ? ["Organizar consultas, propuestas y seguimiento.", "Acordar responsables, fechas y aprobaciones de cada entrega.", "Mostrar con claridad qué haces y para quién tiene valor."] : ["Organize inquiries, proposals and follow-up.", "Agree on owners, dates and approvals for every delivery.", "Show clearly what you do and who benefits."]);
  return <InteriorShell locale={locale}><div className={styles.page}><section className={`container ${styles.heading}`}><p className="section-eyebrow">{commerce ? (es ? "Comercios" : "Retail businesses") : (es ? "Empresas de servicios" : "Service businesses")}</p><h1>{title}</h1><p>{es ? "No necesitas cambiarlo todo a la vez. Empezamos por entender dónde se pierde continuidad y qué vale la pena resolver primero." : "You do not need to change everything at once. We start by understanding where continuity is lost and what is worth solving first."}</p><Link className="button button--primary" href={es ? "/diagnostico?necesidad=ordenar#solicitud" : "/en/diagnosis?need=ordenar#solicitud"}>{es ? "Revisar mi negocio con RCP" : "Review my business with RCP"} ↗</Link></section>
    <section className={`container ${styles.tool}`}><div><Image className={styles.photo} src={`/assets/editorial-v32/${commerce ? "commerce" : "team"}.webp`} width={1200} height={800} sizes="(max-width:760px) 90vw, 45vw" alt={es ? "Fotografía ilustrativa del trabajo cotidiano; no representa un cliente de RCP" : "Illustrative daily work photograph; not an RCP client"} /><p className={styles.note}>{es ? "Fotografía ilustrativa." : "Illustrative photography."}</p></div><div><p className="section-eyebrow">{es ? "Una ruta, tres prioridades" : "One route, three priorities"}</p><h2>{es ? "Que cada paso conecte con el siguiente." : "Help every step connect to the next."}</h2><ol>{steps.map(step => <li key={step}><p>{step}</p></li>)}</ol><div className={styles.links}><Link href={es ? "/servicios/renovacion" : "/en/services/renewal"}>{es ? "Ordenar la operación" : "Organize operations"} ↗</Link><Link href={es ? "/servicios/consultoria" : "/en/services/consulting"}>{es ? "Tomar decisiones con más claridad" : "Make clearer decisions"} ↗</Link><Link href={es ? "/servicios/publicidad" : "/en/services/advertising"}>{es ? "Conectar la marca con sus clientes" : "Connect the brand with its customers"} ↗</Link></div></div></section>
    <section className={`container ${styles.tool}`}><div><h2>{es ? "La tecnología acompaña el proceso." : "Technology supports the process."}</h2><p>{es ? "Evaluamos las herramientas que ya utilizas, las integraciones posibles y lo que necesita desarrollo a la medida. El alcance se acuerda antes de implementar." : "We assess your current tools, possible integrations and what needs custom development. The scope is agreed before implementation."}</p><div className={styles.links}><Link href={es ? "/software-a-la-medida" : "/en/custom-software"}>{es ? "Explorar software a la medida" : "Explore custom software"} ↗</Link><Link href={es ? "/catalogo" : "/en/catalog"}>{es ? "Ver el catálogo de servicios" : "View the service catalog"} ↗</Link><Link href={es ? "/herramientas" : "/en/tools"}>{es ? "Orientarme antes de conversar" : "Explore my starting point"} ↗</Link></div></div><div className={styles.result}><h3>{es ? "Antes de comenzar" : "Before getting started"}</h3><details><summary>{es ? "¿Debo reemplazar mis herramientas?" : "Do I need to replace my tools?"}</summary><p>{es ? "Primero revisamos lo que funciona. La recomendación puede ser organizar, integrar o desarrollar, según el proceso y la viabilidad." : "We first review what works. The recommendation may be to organize, integrate or develop, depending on the process and feasibility."}</p></details><details><summary>{es ? "¿La evaluación tiene costo?" : "Does the assessment have a cost?"}</summary><p>{es ? "La conversación inicial de 45 minutos es sin costo y está sujeta a confirmación. Un diagnóstico posterior o una implementación se cotizan por separado." : "The initial 45-minute conversation is free and subject to confirmation. Further diagnosis or implementation is quoted separately."}</p></details><details><summary>{es ? "¿Qué preparo para la conversación?" : "What should I prepare?"}</summary><p>{es ? "Una descripción del problema, las herramientas que utilizas y el resultado que buscas. No envíes contraseñas ni datos de clientes." : "A description of the problem, the tools you use and the outcome you want. Do not send passwords or customer data."}</p></details></div></section>
  </div></InteriorShell>;
}
